# Wire up travis
language: python
sudo: false

python:
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - pypy3

install: python setup.py dev

script: python setup.py test -q

notifications:
  email:
    - pyramid-checkins@lists.repoze.org
